import pickle
import m2cgen as m2c
import os

print("Loading trained model...")
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(BASE_DIR, "app", "model.pkl")

with open(MODEL_PATH, "rb") as f:
    model = pickle.load(f)

print("Exporting model to JavaScript...")
# Convert the scikit-learn model to pure JavaScript code
code = m2c.export_to_javascript(model)

# The generated code returns a flat array of scores (one per class).
# Let's wrap it in a function that outputs the class with the highest score, mapping it back to the original string label.
classes = list(model.classes_)

wrapper_code = f"""
// Auto-generated by m2cgen
{code}

// Class labels from the trained model
const classes = {classes};

/**
 * Predicts the optimal crop based on input parameters.
 * @param {{object}} input - {{ N, P, K, temperature, humidity, ph, rainfall }}
 * @returns {{string}} The recommended crop.
 */
export function predictCrop(input) {{
    // The model expects an array of features in the exact order they were trained:
    // ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']
    const features = [
        input.N || 0,
        input.P || 0,
        input.K || 0,
        input.temperature || 0,
        input.humidity || 0,
        input.ph || 0,
        input.rainfall || 0
    ];
    
    // Call the m2cgen generated function
    const scores = score(features);
    
    // Find the index with the highest score (RandomForest classification output)
    let maxIdx = 0;
    let maxVal = scores[0];
    for (let i = 1; i < scores.length; i++) {{
        if (scores[i] > maxVal) {{
            maxVal = scores[i];
            maxIdx = i;
        }}
    }}
    
    return classes[maxIdx];
}}
"""

DEST_PATH = os.path.join(BASE_DIR, "..", "..", "web", "src", "utils", "cropModel.js")
os.makedirs(os.path.dirname(DEST_PATH), exist_ok=True)

with open(DEST_PATH, "w") as f:
    f.write(wrapper_code)

print(f"Successfully wrote pure-JS model to: {DEST_PATH}")
