import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, r2_score
import m2cgen as m2c
import os
import json

def train_and_export():
    print("Loading data...")
    # Get absolute paths
    base_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(os.path.dirname(base_dir))
    data_path = os.path.join(root_dir, 'Crop_Yield_Prediction.csv')
    
    df = pd.read_csv(data_path)
    print(f"Dataset shape: {df.shape}")
    
    # Preprocess categorical "Crop" column using LabelEncoder
    le = LabelEncoder()
    df['Crop_encoded'] = le.fit_transform(df['Crop'])
    
    # Save the mapping of string -> integer so JS can use it
    crop_mapping = {crop: int(idx) for idx, crop in enumerate(le.classes_)}
    
    X = df[['Nitrogen', 'Phosphorus', 'Potassium', 'Temperature', 'Humidity', 'pH_Value', 'Rainfall', 'Crop_encoded']]
    y = df['Yield']
    
    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    print("Training RandomForestRegressor...")
    # Limit depth to keep the exported JS file size manageable for browsers
    model = RandomForestRegressor(n_estimators=50, max_depth=10, random_state=42)
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    print(f"Model Mean Absolute Error: {mae:.2f}")
    print(f"Model R^2 Score: {r2:.4f}")
    
    print("Exporting model to JavaScript...")
    code = m2c.export_to_javascript(model)
    
    # Create the JS Wrapper
    wrapper_code = f"""
// Auto-generated by m2cgen
{code}

// Label encoded crop mapping dictionary
const cropMapping = {json.dumps(crop_mapping)};

/**
 * Predicts the expected yield of a crop based on input parameters.
 * @param {{object}} input - {{ Nitrogen, Phosphorus, Potassium, Temperature, Humidity, pH_Value, Rainfall, Crop }}
 * @returns {{number}} The predicted yield.
 */
export function predictYield(input) {{
    // Extract the integer encoding for the crop string name (default to 0 if unknown)
    const cropIdx = cropMapping[input.Crop] || 0;

    // The model expects an array of features in the exact order they were trained:
    // ['Nitrogen', 'Phosphorus', 'Potassium', 'Temperature', 'Humidity', 'pH_Value', 'Rainfall', 'Crop_encoded']
    const features = [
        input.Nitrogen || 0,
        input.Phosphorus || 0,
        input.Potassium || 0,
        input.Temperature || 0,
        input.Humidity || 0,
        input.pH_Value || 0,
        input.Rainfall || 0,
        cropIdx
    ];
    
    // Call the m2cgen generated Regressor function to compute predicted continuous yield
    const predictedYield = score(features);
    
    return predictedYield;
}}
"""

    dest_path = os.path.join(root_dir, "web", "src", "utils", "yieldModel.js")
    os.makedirs(os.path.dirname(dest_path), exist_ok=True)
    
    with open(dest_path, "w") as f:
        f.write(wrapper_code)

    print(f"Successfully wrote pure-JS yield model to: {dest_path}")

if __name__ == "__main__":
    train_and_export()
